### ISSUE TITLE
Error in charger

### ISSUE THREAD

**Issue by Jailander** [strands-project/scitos_robot#26]
Hi we just had a funny error in the charger Linda was docked but not charging and the charging station had the charging and error LEDs blinking.

![20131106_152515](https://f.cloud.github.com/assets/5035967/1484814/f57a76dc-470b-11e3-8cd3-b61bdf763f6f.jpg)

(Sorry about the picture it wasn't easy to take it when the lights were on)

We tried to solved it by undocking and placing Linda back in the station but it didn't work, and then we unplugged the station until all lights went off and then plug it again and that solved the problem (classic rebooting), however, we would like to know what this means, @chmartin21 can you tell us?

**Comment by chmartin21** [comment]
I will ask our hardware engineers to comment on this.

**Comment by ml-stu** [comment]
This is the first time I hear about such an error. I think there was a temporary problem at the power supply unit inside the ACS. It did not activate the power output.

Bisher habe ich noch nicht von einem solchen Fehler gehört. Vermutlich kam das in der Ladestation integrierte Netzteil in einen Fehlerzustand, so dass die Ausgangsspannung dieses Netzteils nicht mehr zugeschaltet werden konnte. Der Mikrocontroller der Ladestation hat das Netzteil aktiviert, die Spannung stieg jedoch nicht auf den zu erwartenden Wert, es wird ein Fehler gemeldet. Da ebenso kein Ladestrom fließt, wird das Netzteil nach wenigen Sekunden wieder abgeschalten. Kurz darauf kommt der nächste Start-Befehl vom Roboter und das ganze geht von vorn los.

**Comment by Jailander** [comment]
Yes that seems to be the problem we had, we will let you know if it happens again.

Ja, das koennte genau das Problem sein, dass wir hatten. Wir melden uns falls es nochmal auftreten sollte.

**Comment by Jailander** [comment]
Hi,
I just notice a completely new error in Linda's Charger, whilst Linda was in the charger it started showing the following behaviour:
the green led only was on for one second then the error led was on for two seconds (first image) and then the yellow led was on for one more second (second image), and this was repeated continously, I removed Linda from the docking station but this behaviour continued the only solution was to turn the charging station off an then on again
![charger1](https://f.cloud.github.com/assets/5035967/2057795/ad91a83c-8b4d-11e3-84e1-eb3e724ec248.jpg)
![charger2](https://f.cloud.github.com/assets/5035967/2057794/ad91a148-8b4d-11e3-887e-74c867e2acf2.jpg)

can this error be related to issue #35???

P.S: next time I'll make a video instead of images

**Comment by Jailander** [comment]
Hi it happened again, here is a video showing the error with linda and without her on the charger:
https://www.youtube.com/watch?v=fvX9Uu7cpis

**Comment by ml-stu** [comment]
We do not think, that this error is relatet to #35.
The behaviour of the charging station is very strange. We plan to replace the two main components inside the charging station: The power supply unit and the controller circuit board.
Do you see the possibility to change these parts yourself? So you do not have to send the whole CHarging station back for repair. Do you have access to some metric tools (5.5mm socket wrench, 2mm, 2.5mm and 3mm hexagon socket and the convenient Torx for the screws at the front plate)?

**Comment by Jailander** [comment]
Hi, that shouldn't be any problem for us,

Can you send us the pieces first? so we can use the robot meanwhile

**Comment by ml-stu** [comment]
Yes we will send it together with the new charger (#35). They will leave Ilmenau on Thursday or Friday.

**Comment by Jailander** [comment]
Great!!!!, Thank you very much we will send you back the other pieces as soon as we replace them.

**Comment by Jailander** [comment]
Hi, we just received the pieces, there are three different components, but we have no idea where they belong, can you send us some instructions on how to install them?

**Comment by ml-stu** [comment]
ok, here we go:

part no 1: a small PCB
![dsc02037](https://f.cloud.github.com/assets/5874322/2150879/9bcd6bfc-9405-11e3-9742-b3801bd972f1.JPG)

part no 2: power supply unit (with the fan)
![dsc02033](https://f.cloud.github.com/assets/5874322/2150881/a334fb94-9405-11e3-97bc-ae8b29b52f22.JPG)

part no 3: robots charger (without fan)
![dsc02029](https://f.cloud.github.com/assets/5874322/2150889/b07d2d26-9405-11e3-8278-68e0079b0f0d.JPG)

Let's start with the charging station:

At first remove the robot from the charging station and disconnect mains from it. Wait until all LEDs are off. Open the front of the charging station (the side facing the robot), you will need a torx screw driver. Pay attention, the front plate is connected to the charging station by a wire. It should look like this inside

![acs](https://f.cloud.github.com/assets/5874322/2151029/fe98007a-9406-11e3-9c0c-371c328e8ea8.JPG)

Replace the power supply unit and the PCB with the new components.
If you can find four Allen head screws on the back side of the charging station, these are used to fix the power supply unit. If not, remove the nuts, which hold the aluminium plate, on which the power supply is fastend.
All cables are provided with plug and socket or they are screwd to the PCB or power supply unit.  
Use the attached photo or make your own photos to be sure to restore the correct cabling.

Tighten all screws, attach the front plate and test the charging station.

To replace the charger remove the lower cover from the robot (after switching the robot of by key switch). The charger is mounted on the left of the robot, at the dowside of the second mounting plate. At first remove all plugs from it (the cables should be fixed at the robot so that no wrong plugging is possible) and these two screws with the cable brackets:
![dsc02029](https://f.cloud.github.com/assets/5874322/2151278/c87e8574-9409-11e3-9feb-2cb4e5847c77.JPG)

Then remove the four screws at the top:
![dsc02028](https://f.cloud.github.com/assets/5874322/2151284/d61a13ec-9409-11e3-92df-c4c6f35be6d2.JPG)

Now the charger is only hold by the heat sink paste. Jiggling or pushing the last screw only down while unscrewing will help losen the charger.

You do not need to use new heat sink paste. Attach the new charger in reverse order.

**Comment by Jailander** [comment]
Thank you very much, we'll do it tomorrow and send you back the other parts

**Comment by Jailander** [comment]
Hi, We already replaced the pieces, we noticed this behaviour on the charger http://youtu.be/IW-odD6zXOk but we think it may be the desired behaviour since the battery was at 100% charge, is this right?

**Comment by ml-stu** [comment]
Yes, it is right when the embedded pc is shut down ant the batteries are at 100% charge.

**Comment by Jailander** [comment]
Hi, this is weird because the PC was on, however the control nodes were not running, can this be the reason?

**Comment by cburbridge** [comment]
@Jailander I think you guys solved this so I have closed the issue. Please re-open if not.

**Comment by Jailander** [comment]
yes it is thank you
