### ISSUE TITLE
using chest and head camera simultaneously 

### ISSUE THREAD

**Issue by ToMadoRe** [strands-project/scitos_robot#29]
I have some problems starting our robot with chest and head camera connected at the same time. 
If both are plugged in, we are not even able to boot our PC (it gets stuck shortly after the BIOS setup).
I somehow managed to get both running yesterday, but this seems impossible at the moment. I even tried to plug the head camera in after starting Ubuntu, which causes the system to freeze.

We are currently using the chest cam, sound, touch screen and an additional USB hub (joystick and keyboard) as USB 2.0 ports. The only thing connected to USB3.0 is the head cam.

Has anyone else experienced this problem?

**Comment by RaresAmbrus** [comment]
We had some issues getting both cameras running at first, but when we moved one of them on USB 3.0 things started working. What I would suggest is:
- enable USB 3.0 in BIOS
- make sure the cameras are connected on separate USB buses (lsusb)
- start the robot after the cameras have been plugged in. 
- check on rviz to see if you're getting depth and RGB feeds from both the cameras.

**Comment by ToMadoRe** [comment]
I did all of the first points, but the robot does not boot. There is just a black screen with a blinking cursors right before the GRUB menu should show up.

**Comment by RaresAmbrus** [comment]
This is strange, not something that happened to us. Is it possible to boot the system if you remove both cameras?

**Comment by ToMadoRe** [comment]
I can boot the system if i unplug the head cam from usb3.0. However, I can plug it in as soon as the GRUB menu appears. If it is plugged in before, the robot doesn't start.

**Comment by bfalacerda** [comment]
We are also having some problems. When we launch scitos_bringup, we have the following:

process[OpenniWrapperNodelet-7]: started with pid [14379]
[ INFO] [1384965623.678038499]: Loading nodelet /OpenniWrapperNodelet of type openni_wrapper/OpenniWrapperNodelet to manager standalone_nodelet with the following remappings:
Namsespace for devices 1 and 2 will NOT be swapped.
Devices defined 2
head_xtion
chest_xtion
Openni initialized
Device "1d27/0601@2/6" already connected
Device "1d27/0601@3/3" already connected
Number of devices connected 2
Warning: USB events thread - failed to set priority. This might cause loss of data...
process[manager-8]: started with pid [14423]
[ INFO] [1384965623.851058179]: Not loading with MIRA multiprocess support.
[ INFO] [1384965623.931711942]: Initializing nodelet with 4 worker threads.

---

 *\* This software uses MetraLabs 'MIRA Commercial Edition'.  **
 *\*   http://www.metralabs.com                               **
 *\* Copyright (C) MetraLabs GmbH, Germany                    **

---

 *\* License information:                                     **
 *\*   License ID : 10386-0001                                **
 *\*   Issue date : 2013-Jun-14 07:01:15.062291               **
 *\*   Vendor     : MetraLabs GmbH, Germany                   **
 *\*   Licensee   : University of Birmingham                  **

---

 *\* Redistribution and modification of this software is      **
 *\* strictly prohibited.                                     **

---

process[image_proc_head_xtion-9]: started with pid [14465]
Opened device 1d27/0601@2/6   namespace head_xtion
This device supports the following sensors IR COLOR DEPTH 
Image registration NOT SUPPORTED
process[rectify_depth_head_xtion-10]: started with pid [14502]
process[metric_rect_head_xtion-11]: started with pid [14588]
[ WARN] [1384965624.523076050]: (MIRA) Failed to convert value from string '', in tag starting at: (0)
[WARNING ] 2013-Nov-20 16:40:24.523036 Failed to convert value from string '', in tag starting at: (0)
process[points_head_xtion-12]: started with pid [14701]
[ WARN] [1384965624.802636392]: (MIRA) Dropping data (slot) in channel '/robot/can/OutgoingCAN' since slot with same timestamp already exists
[WARNING ] 2013-Nov-20 16:40:24.802569 Dropping data (slot) in channel '/robot/can/OutgoingCAN' since slot with same timestamp already exists
[ WARN] [1384965624.869789143]: (MIRA) /robot/#MainControlUnit_fcab7cbf-eddf-4d9c-a0ca-81600aa73859 : Booting up
[WARNING ] 2013-Nov-20 16:40:24.869741 /robot/#MainControlUnit_fcab7cbf-eddf-4d9c-a0ca-81600aa73859 : Booting up
process[register_depth_rgb_head_xtion-13]: started with pid [14804]
process[points_xyzrgb_depth_rgb_head_xtion-14]: started with pid [14913]
process[disparity_depth_head_xtion-15]: started with pid [15005]
process[manager_head_xtion-16]: started with pid [15054]
[ INFO] [1384965625.718802546]: Initializing nodelet with 4 worker threads.
process[image_proc_chest_xtion-17]: started with pid [15118]
process[rectify_depth_chest_xtion-18]: started with pid [15160]
process[metric_rect_chest_xtion-19]: started with pid [15232]
process[points_chest_xtion-20]: started with pid [15364]
process[register_depth_rgb_chest_xtion-21]: started with pid [15440]
process[points_xyzrgb_depth_rgb_chest_xtion-22]: started with pid [15529]
process[disparity_depth_chest_xtion-23]: started with pid [15615]
process[joint_state_publisher-24]: started with pid [15669]
process[robot_state_publisher-25]: started with pid [15718]
process[robot_pose_publisher-26]: started with pid [15748]
process[chest_calibration_publisher-27]: started with pid [15792]
process[pc_monitor-28]: started with pid [15808]
process[diagnostic_aggregator-29]: started with pid [15813]
[ INFO] [1384965628.992744439]: Creating G5 with modules [Drive Charger EBC Display Head]
[ INFO] [1384965629.002893137]: Creating SCITOS G5 instance.
[ INFO] [1384965629.002952434]: Initialising Drive module..
[ INFO] [1384965629.002969760]: Initialising Charger module..
[ INFO] [1384965629.009027350]: Initialising EBC module..
[ INFO] [1384965629.040812604]: Initialising Display module..
[ INFO] [1384965629.056492299]: Initialising Head module..
[ INFO] [1384965629.139667600]: Reconfigure request on ScitosDisplay module.
[ INFO] [1384965629.152826827]: Going into main loop.
[ INFO] [1384965638.130453632]: Stopping to publish chest transform after 10 seconds, quitting...
[chest_calibration_publisher-27] process has finished cleanly
log file: /home/strands/.ros/log/71db27c0-5202-11e3-aa87-843a4b7f1c04/chest_calibration_publisher-27*.log

Bit after a while, immediately after the last line above, we get:

Couldn't open device
    Could not open "1d27/0601@3/3": USB transfer timeout!

head_xtion is publishing stuff but chest_xtion does not publish anything

Any idea on this, @RaresAmbrus ?

**Comment by RaresAmbrus** [comment]
Seems like one of the cameras isn't opened properly. The only thing that worked for me was rebooting the robot, and if that doesn't solve it, trying a different combination of USB ports.

**Comment by bfalacerda** [comment]
we already tried rebooting and it didn't work. The thing is that the setup is exactly the same as before, and it was working

**Comment by RaresAmbrus** [comment]
That is strange; in our case, once we found a working combination of USB ports the cameras were opening properly. Other than changing the USB ports I can't really think of any other way to fix this. 
You could try checking the /etc/openni/GlobalDefaults.ini file and commenting out the UsbInterface line.

**Comment by ToMadoRe** [comment]
Ours is also working randomly. Once a particular combination of USB ports is working and the next time there are problems with the same combination. Trying a different combination, plugging the camera in at the right time and having some luck, sometimes solves the problem. Don't really know what to do anymore. Our marathon environment isn't made for laser only navigation.

**Comment by bfalacerda** [comment]
We commented the UsbInterface line in /etc/openni/GlobalDefaults.ini  and rebooted and it worked. I'm not sure if it was luck though. Maybe you can also try it @ToMadoRe

**Comment by ghost** [comment]
We also commented it out, but it remains random. We don't neef to restart
the robot though. Often restarting bringup is enough already.

**Comment by ToMadoRe** [comment]
Okay, I will try to comment this line and see if it changes anything. I guess this affects both cameras then? I am also wondering who is still using the "original" Asus (xxx0601) and who replaced it by the xxx0600 as discussed in e.g.  https://github.com/strands-project/scitos_robot/issues/18 
Maybe things are different then. We are still using the xxx0601

**Comment by mzillich** [comment]
Seeing that we have so many difficulties with two cameras, and that we need the chest camera in our environment (and at AAF!), can we use just the chest?
could we mount the "robot station" marker at chest height (or slightly lower)?

**Comment by hawesie** [comment]
Or alternatively replace the head cam with a standard webcam.

**Comment by ToMadoRe** [comment]
That's what I am testing right now... Looking good so far

**Comment by cdondrup** [comment]
Is there any new development on this?
I just tried to run both cameras which works initially but after a while the head_xtion stops publishing a depth image.

Regarding the workaround with only the chest camera in use, this is not a solution imho:
- 3D mapping won't work properly (e.g. no ptu sweeps and just 3D mapping up to 1.5 meters height)
- no people perception

**Comment by cburbridge** [comment]
I think this was solved by openni wrappers @RaresAmbrus. We had no problem at the security deployment, so I will close.
