### ISSUE TITLE
Udev rules

### ISSUE THREAD

**Issue by gestom** [strands-project/scitos_robot#31]
@chmartin21 : 
Hi, 
I have a question regarding numbering the robot devices:

Sometimes (30% of cases), the ROS fails to start, because neither the SICK nor CAN are sending data. Trying to launch ROS again does not help and the only solution is rebooting the PC. I had a look at the system configuration and found out that both the SICK and CAN are connected through an quad FTDI and appear as ttyUSB0 and ttyUSB2 respectively. 

So my question is if it might happen that the ttyUSB0 and ttyUSB2 might swap occationally, so ROS would try to communicate with the SICK thinking it is the CAN and vice versa.

**Comment by chmartin21** [comment]
Hi!

the MCU (main control unit) of the robot is equipped with a FTDI chip, which provides 4 high-speed serial devices. If there are no other FTDI (or similar) devices are connected to the robot, they always appear as /dev/ttyUSB0...3. Since this is only one chip with 4 ports, the order of the ports is always the same. I can't see a way, how /dev/ttyUSB0 and /dev/ttyUSB2 might swap. But if you connect another FTDI device, the devices e.g. might shift to /dev/ttyUSB1...4.

**Comment by cburbridge** [comment]
@gestrom solved? Re-open if not.
